//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tableta_Rosetta.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubjectInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SubjectInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SubjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubjectName {
            get {
                return this.SubjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectNameField, value) != true)) {
                    this.SubjectNameField = value;
                    this.RaisePropertyChanged("SubjectName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTextField;
        
        private int CountAskedField;
        
        private int CountRightField;
        
        private int LevelKnownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string QuestionText {
            get {
                return this.QuestionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTextField, value) != true)) {
                    this.QuestionTextField = value;
                    this.RaisePropertyChanged("QuestionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CountAsked {
            get {
                return this.CountAskedField;
            }
            set {
                if ((this.CountAskedField.Equals(value) != true)) {
                    this.CountAskedField = value;
                    this.RaisePropertyChanged("CountAsked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CountRight {
            get {
                return this.CountRightField;
            }
            set {
                if ((this.CountRightField.Equals(value) != true)) {
                    this.CountRightField = value;
                    this.RaisePropertyChanged("CountRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LevelKnown {
            get {
                return this.LevelKnownField;
            }
            set {
                if ((this.LevelKnownField.Equals(value) != true)) {
                    this.LevelKnownField = value;
                    this.RaisePropertyChanged("LevelKnown");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RightAnswerInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RightAnswerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AnswerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AnswerId {
            get {
                return this.AnswerIdField;
            }
            set {
                if ((this.AnswerIdField.Equals(value) != true)) {
                    this.AnswerIdField = value;
                    this.RaisePropertyChanged("AnswerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AnswerText {
            get {
                return this.AnswerTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerTextField, value) != true)) {
                    this.AnswerTextField = value;
                    this.RaisePropertyChanged("AnswerText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WrongAnswersInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WrongAnswersInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int WrongAnswerId1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WrongAnswerText1Field;
        
        private int WrongAnswerId2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WrongAnswerText2Field;
        
        private int WrongAnswerId3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WrongAnswerText3Field;
        
        private int WrongAnswerId4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WrongAnswerText4Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int WrongAnswerId1 {
            get {
                return this.WrongAnswerId1Field;
            }
            set {
                if ((this.WrongAnswerId1Field.Equals(value) != true)) {
                    this.WrongAnswerId1Field = value;
                    this.RaisePropertyChanged("WrongAnswerId1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WrongAnswerText1 {
            get {
                return this.WrongAnswerText1Field;
            }
            set {
                if ((object.ReferenceEquals(this.WrongAnswerText1Field, value) != true)) {
                    this.WrongAnswerText1Field = value;
                    this.RaisePropertyChanged("WrongAnswerText1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int WrongAnswerId2 {
            get {
                return this.WrongAnswerId2Field;
            }
            set {
                if ((this.WrongAnswerId2Field.Equals(value) != true)) {
                    this.WrongAnswerId2Field = value;
                    this.RaisePropertyChanged("WrongAnswerId2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WrongAnswerText2 {
            get {
                return this.WrongAnswerText2Field;
            }
            set {
                if ((object.ReferenceEquals(this.WrongAnswerText2Field, value) != true)) {
                    this.WrongAnswerText2Field = value;
                    this.RaisePropertyChanged("WrongAnswerText2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int WrongAnswerId3 {
            get {
                return this.WrongAnswerId3Field;
            }
            set {
                if ((this.WrongAnswerId3Field.Equals(value) != true)) {
                    this.WrongAnswerId3Field = value;
                    this.RaisePropertyChanged("WrongAnswerId3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WrongAnswerText3 {
            get {
                return this.WrongAnswerText3Field;
            }
            set {
                if ((object.ReferenceEquals(this.WrongAnswerText3Field, value) != true)) {
                    this.WrongAnswerText3Field = value;
                    this.RaisePropertyChanged("WrongAnswerText3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int WrongAnswerId4 {
            get {
                return this.WrongAnswerId4Field;
            }
            set {
                if ((this.WrongAnswerId4Field.Equals(value) != true)) {
                    this.WrongAnswerId4Field = value;
                    this.RaisePropertyChanged("WrongAnswerId4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string WrongAnswerText4 {
            get {
                return this.WrongAnswerText4Field;
            }
            set {
                if ((object.ReferenceEquals(this.WrongAnswerText4Field, value) != true)) {
                    this.WrongAnswerText4Field = value;
                    this.RaisePropertyChanged("WrongAnswerText4");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionDataInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QuestionDataInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerTextField;
        
        private int CountAskedField;
        
        private int CountRightField;
        
        private double LevelKnownField;
        
        private int QuestionIdField;
        
        private int AnswerIdField;
        
        private int SubjectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubjectName {
            get {
                return this.SubjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectNameField, value) != true)) {
                    this.SubjectNameField = value;
                    this.RaisePropertyChanged("SubjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string QuestionText {
            get {
                return this.QuestionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTextField, value) != true)) {
                    this.QuestionTextField = value;
                    this.RaisePropertyChanged("QuestionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AnswerText {
            get {
                return this.AnswerTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerTextField, value) != true)) {
                    this.AnswerTextField = value;
                    this.RaisePropertyChanged("AnswerText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CountAsked {
            get {
                return this.CountAskedField;
            }
            set {
                if ((this.CountAskedField.Equals(value) != true)) {
                    this.CountAskedField = value;
                    this.RaisePropertyChanged("CountAsked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CountRight {
            get {
                return this.CountRightField;
            }
            set {
                if ((this.CountRightField.Equals(value) != true)) {
                    this.CountRightField = value;
                    this.RaisePropertyChanged("CountRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double LevelKnown {
            get {
                return this.LevelKnownField;
            }
            set {
                if ((this.LevelKnownField.Equals(value) != true)) {
                    this.LevelKnownField = value;
                    this.RaisePropertyChanged("LevelKnown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int AnswerId {
            get {
                return this.AnswerIdField;
            }
            set {
                if ((this.AnswerIdField.Equals(value) != true)) {
                    this.AnswerIdField = value;
                    this.RaisePropertyChanged("AnswerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name subject from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSubject", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.AddSubjectResponse AddSubject(Tableta_Rosetta.ServiceReference1.AddSubjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.AddSubjectResponse> AddSubjectAsync(Tableta_Rosetta.ServiceReference1.AddSubjectRequest request);
        
        // CODEGEN: Generating message contract since element name GetSubjectsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubjects", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.GetSubjectsResponse GetSubjects(Tableta_Rosetta.ServiceReference1.GetSubjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubjects", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetSubjectsResponse> GetSubjectsAsync(Tableta_Rosetta.ServiceReference1.GetSubjectsRequest request);
        
        // CODEGEN: Generating message contract since element name question from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddQuestion", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.AddQuestionResponse AddQuestion(Tableta_Rosetta.ServiceReference1.AddQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddQuestion", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.AddQuestionResponse> AddQuestionAsync(Tableta_Rosetta.ServiceReference1.AddQuestionRequest request);
        
        // CODEGEN: Generating message contract since element name answer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAnswer", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.AddAnswerResponse AddAnswer(Tableta_Rosetta.ServiceReference1.AddAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAnswer", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.AddAnswerResponse> AddAnswerAsync(Tableta_Rosetta.ServiceReference1.AddAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RightAnswerSubmited", ReplyAction="*")]
        void RightAnswerSubmited(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RightAnswerSubmited", ReplyAction="*")]
        System.Threading.Tasks.Task RightAnswerSubmitedAsync(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WrongAnswerSubmited", ReplyAction="*")]
        void WrongAnswerSubmited(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WrongAnswerSubmited", ReplyAction="*")]
        System.Threading.Tasks.Task WrongAnswerSubmitedAsync(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnswerShown", ReplyAction="*")]
        void AnswerShown(int answerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnswerShown", ReplyAction="*")]
        System.Threading.Tasks.Task AnswerShownAsync(int answerId);
        
        // CODEGEN: Generating message contract since element name GetRandomQuestionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandomQuestion", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.GetRandomQuestionResponse GetRandomQuestion(Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandomQuestion", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetRandomQuestionResponse> GetRandomQuestionAsync(Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequest request);
        
        // CODEGEN: Generating message contract since element name RightAnswerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RightAnswer", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.RightAnswerResponse RightAnswer(Tableta_Rosetta.ServiceReference1.RightAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RightAnswer", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.RightAnswerResponse> RightAnswerAsync(Tableta_Rosetta.ServiceReference1.RightAnswerRequest request);
        
        // CODEGEN: Generating message contract since element name GetRandomWrongAnswersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandomWrongAnswers", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersResponse GetRandomWrongAnswers(Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandomWrongAnswers", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersResponse> GetRandomWrongAnswersAsync(Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequest request);
        
        // CODEGEN: Generating message contract since element name GetQuestionStatisticsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuestionStatistics", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsResponse GetQuestionStatistics(Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuestionStatistics", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsResponse> GetQuestionStatisticsAsync(Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequest request);
        
        // CODEGEN: Generating message contract since element name GetQuestionDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuestionData", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.GetQuestionDataResponse GetQuestionData(Tableta_Rosetta.ServiceReference1.GetQuestionDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuestionData", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetQuestionDataResponse> GetQuestionDataAsync(Tableta_Rosetta.ServiceReference1.GetQuestionDataRequest request);
        
        // CODEGEN: Generating message contract since element name questionText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateData", ReplyAction="*")]
        Tableta_Rosetta.ServiceReference1.UpdateDataResponse UpdateData(Tableta_Rosetta.ServiceReference1.UpdateDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateData", ReplyAction="*")]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.UpdateDataResponse> UpdateDataAsync(Tableta_Rosetta.ServiceReference1.UpdateDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSubjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSubject", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.AddSubjectRequestBody Body;
        
        public AddSubjectRequest() {
        }
        
        public AddSubjectRequest(Tableta_Rosetta.ServiceReference1.AddSubjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSubjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string subject;
        
        public AddSubjectRequestBody() {
        }
        
        public AddSubjectRequestBody(string subject) {
            this.subject = subject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSubjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSubjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.AddSubjectResponseBody Body;
        
        public AddSubjectResponse() {
        }
        
        public AddSubjectResponse(Tableta_Rosetta.ServiceReference1.AddSubjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddSubjectResponseBody {
        
        public AddSubjectResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubjects", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetSubjectsRequestBody Body;
        
        public GetSubjectsRequest() {
        }
        
        public GetSubjectsRequest(Tableta_Rosetta.ServiceReference1.GetSubjectsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSubjectsRequestBody {
        
        public GetSubjectsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubjectsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetSubjectsResponseBody Body;
        
        public GetSubjectsResponse() {
        }
        
        public GetSubjectsResponse(Tableta_Rosetta.ServiceReference1.GetSubjectsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSubjectsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tableta_Rosetta.ServiceReference1.SubjectInfo[] GetSubjectsResult;
        
        public GetSubjectsResponseBody() {
        }
        
        public GetSubjectsResponseBody(Tableta_Rosetta.ServiceReference1.SubjectInfo[] GetSubjectsResult) {
            this.GetSubjectsResult = GetSubjectsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddQuestionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddQuestion", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.AddQuestionRequestBody Body;
        
        public AddQuestionRequest() {
        }
        
        public AddQuestionRequest(Tableta_Rosetta.ServiceReference1.AddQuestionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddQuestionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string question;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int subject;
        
        public AddQuestionRequestBody() {
        }
        
        public AddQuestionRequestBody(string question, int subject) {
            this.question = question;
            this.subject = subject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddQuestionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddQuestionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.AddQuestionResponseBody Body;
        
        public AddQuestionResponse() {
        }
        
        public AddQuestionResponse(Tableta_Rosetta.ServiceReference1.AddQuestionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddQuestionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddQuestionResult;
        
        public AddQuestionResponseBody() {
        }
        
        public AddQuestionResponseBody(int AddQuestionResult) {
            this.AddQuestionResult = AddQuestionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAnswerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAnswer", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.AddAnswerRequestBody Body;
        
        public AddAnswerRequest() {
        }
        
        public AddAnswerRequest(Tableta_Rosetta.ServiceReference1.AddAnswerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAnswerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string answer;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int questionId;
        
        public AddAnswerRequestBody() {
        }
        
        public AddAnswerRequestBody(string answer, int questionId) {
            this.answer = answer;
            this.questionId = questionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAnswerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAnswerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.AddAnswerResponseBody Body;
        
        public AddAnswerResponse() {
        }
        
        public AddAnswerResponse(Tableta_Rosetta.ServiceReference1.AddAnswerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddAnswerResponseBody {
        
        public AddAnswerResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomQuestionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomQuestion", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequestBody Body;
        
        public GetRandomQuestionRequest() {
        }
        
        public GetRandomQuestionRequest(Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRandomQuestionRequestBody {
        
        public GetRandomQuestionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomQuestionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomQuestionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetRandomQuestionResponseBody Body;
        
        public GetRandomQuestionResponse() {
        }
        
        public GetRandomQuestionResponse(Tableta_Rosetta.ServiceReference1.GetRandomQuestionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRandomQuestionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tableta_Rosetta.ServiceReference1.Question GetRandomQuestionResult;
        
        public GetRandomQuestionResponseBody() {
        }
        
        public GetRandomQuestionResponseBody(Tableta_Rosetta.ServiceReference1.Question GetRandomQuestionResult) {
            this.GetRandomQuestionResult = GetRandomQuestionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RightAnswerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RightAnswer", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.RightAnswerRequestBody Body;
        
        public RightAnswerRequest() {
        }
        
        public RightAnswerRequest(Tableta_Rosetta.ServiceReference1.RightAnswerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RightAnswerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int questionId;
        
        public RightAnswerRequestBody() {
        }
        
        public RightAnswerRequestBody(int questionId) {
            this.questionId = questionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RightAnswerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RightAnswerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.RightAnswerResponseBody Body;
        
        public RightAnswerResponse() {
        }
        
        public RightAnswerResponse(Tableta_Rosetta.ServiceReference1.RightAnswerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RightAnswerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tableta_Rosetta.ServiceReference1.RightAnswerInfo RightAnswerResult;
        
        public RightAnswerResponseBody() {
        }
        
        public RightAnswerResponseBody(Tableta_Rosetta.ServiceReference1.RightAnswerInfo RightAnswerResult) {
            this.RightAnswerResult = RightAnswerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomWrongAnswersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomWrongAnswers", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequestBody Body;
        
        public GetRandomWrongAnswersRequest() {
        }
        
        public GetRandomWrongAnswersRequest(Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRandomWrongAnswersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int questionId;
        
        public GetRandomWrongAnswersRequestBody() {
        }
        
        public GetRandomWrongAnswersRequestBody(int questionId) {
            this.questionId = questionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRandomWrongAnswersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRandomWrongAnswersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersResponseBody Body;
        
        public GetRandomWrongAnswersResponse() {
        }
        
        public GetRandomWrongAnswersResponse(Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRandomWrongAnswersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tableta_Rosetta.ServiceReference1.WrongAnswersInfo GetRandomWrongAnswersResult;
        
        public GetRandomWrongAnswersResponseBody() {
        }
        
        public GetRandomWrongAnswersResponseBody(Tableta_Rosetta.ServiceReference1.WrongAnswersInfo GetRandomWrongAnswersResult) {
            this.GetRandomWrongAnswersResult = GetRandomWrongAnswersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestionStatistics", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequestBody Body;
        
        public GetQuestionStatisticsRequest() {
        }
        
        public GetQuestionStatisticsRequest(Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetQuestionStatisticsRequestBody {
        
        public GetQuestionStatisticsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestionStatisticsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsResponseBody Body;
        
        public GetQuestionStatisticsResponse() {
        }
        
        public GetQuestionStatisticsResponse(Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuestionStatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tableta_Rosetta.ServiceReference1.ArrayOfInt GetQuestionStatisticsResult;
        
        public GetQuestionStatisticsResponseBody() {
        }
        
        public GetQuestionStatisticsResponseBody(Tableta_Rosetta.ServiceReference1.ArrayOfInt GetQuestionStatisticsResult) {
            this.GetQuestionStatisticsResult = GetQuestionStatisticsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestionData", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetQuestionDataRequestBody Body;
        
        public GetQuestionDataRequest() {
        }
        
        public GetQuestionDataRequest(Tableta_Rosetta.ServiceReference1.GetQuestionDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetQuestionDataRequestBody {
        
        public GetQuestionDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuestionDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuestionDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.GetQuestionDataResponseBody Body;
        
        public GetQuestionDataResponse() {
        }
        
        public GetQuestionDataResponse(Tableta_Rosetta.ServiceReference1.GetQuestionDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuestionDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tableta_Rosetta.ServiceReference1.QuestionDataInfo[] GetQuestionDataResult;
        
        public GetQuestionDataResponseBody() {
        }
        
        public GetQuestionDataResponseBody(Tableta_Rosetta.ServiceReference1.QuestionDataInfo[] GetQuestionDataResult) {
            this.GetQuestionDataResult = GetQuestionDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateData", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.UpdateDataRequestBody Body;
        
        public UpdateDataRequest() {
        }
        
        public UpdateDataRequest(Tableta_Rosetta.ServiceReference1.UpdateDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int questionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int answerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int subjectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string questionText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string answerText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int countAsked;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int countRight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public double levelKnown;
        
        public UpdateDataRequestBody() {
        }
        
        public UpdateDataRequestBody(int questionId, int answerId, int subjectId, string questionText, string answerText, int countAsked, int countRight, double levelKnown) {
            this.questionId = questionId;
            this.answerId = answerId;
            this.subjectId = subjectId;
            this.questionText = questionText;
            this.answerText = answerText;
            this.countAsked = countAsked;
            this.countRight = countRight;
            this.levelKnown = levelKnown;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tableta_Rosetta.ServiceReference1.UpdateDataResponseBody Body;
        
        public UpdateDataResponse() {
        }
        
        public UpdateDataResponse(Tableta_Rosetta.ServiceReference1.UpdateDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateDataResponseBody {
        
        public UpdateDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Tableta_Rosetta.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Tableta_Rosetta.ServiceReference1.WebService1Soap>, Tableta_Rosetta.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.AddSubjectResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.AddSubject(Tableta_Rosetta.ServiceReference1.AddSubjectRequest request) {
            return base.Channel.AddSubject(request);
        }
        
        public void AddSubject(string subject) {
            Tableta_Rosetta.ServiceReference1.AddSubjectRequest inValue = new Tableta_Rosetta.ServiceReference1.AddSubjectRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.AddSubjectRequestBody();
            inValue.Body.subject = subject;
            Tableta_Rosetta.ServiceReference1.AddSubjectResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).AddSubject(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.AddSubjectResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.AddSubjectAsync(Tableta_Rosetta.ServiceReference1.AddSubjectRequest request) {
            return base.Channel.AddSubjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.AddSubjectResponse> AddSubjectAsync(string subject) {
            Tableta_Rosetta.ServiceReference1.AddSubjectRequest inValue = new Tableta_Rosetta.ServiceReference1.AddSubjectRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.AddSubjectRequestBody();
            inValue.Body.subject = subject;
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).AddSubjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.GetSubjectsResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.GetSubjects(Tableta_Rosetta.ServiceReference1.GetSubjectsRequest request) {
            return base.Channel.GetSubjects(request);
        }
        
        public Tableta_Rosetta.ServiceReference1.SubjectInfo[] GetSubjects() {
            Tableta_Rosetta.ServiceReference1.GetSubjectsRequest inValue = new Tableta_Rosetta.ServiceReference1.GetSubjectsRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetSubjectsRequestBody();
            Tableta_Rosetta.ServiceReference1.GetSubjectsResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetSubjects(inValue);
            return retVal.Body.GetSubjectsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetSubjectsResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.GetSubjectsAsync(Tableta_Rosetta.ServiceReference1.GetSubjectsRequest request) {
            return base.Channel.GetSubjectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetSubjectsResponse> GetSubjectsAsync() {
            Tableta_Rosetta.ServiceReference1.GetSubjectsRequest inValue = new Tableta_Rosetta.ServiceReference1.GetSubjectsRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetSubjectsRequestBody();
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetSubjectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.AddQuestionResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.AddQuestion(Tableta_Rosetta.ServiceReference1.AddQuestionRequest request) {
            return base.Channel.AddQuestion(request);
        }
        
        public int AddQuestion(string question, int subject) {
            Tableta_Rosetta.ServiceReference1.AddQuestionRequest inValue = new Tableta_Rosetta.ServiceReference1.AddQuestionRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.AddQuestionRequestBody();
            inValue.Body.question = question;
            inValue.Body.subject = subject;
            Tableta_Rosetta.ServiceReference1.AddQuestionResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).AddQuestion(inValue);
            return retVal.Body.AddQuestionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.AddQuestionResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.AddQuestionAsync(Tableta_Rosetta.ServiceReference1.AddQuestionRequest request) {
            return base.Channel.AddQuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.AddQuestionResponse> AddQuestionAsync(string question, int subject) {
            Tableta_Rosetta.ServiceReference1.AddQuestionRequest inValue = new Tableta_Rosetta.ServiceReference1.AddQuestionRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.AddQuestionRequestBody();
            inValue.Body.question = question;
            inValue.Body.subject = subject;
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).AddQuestionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.AddAnswerResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.AddAnswer(Tableta_Rosetta.ServiceReference1.AddAnswerRequest request) {
            return base.Channel.AddAnswer(request);
        }
        
        public void AddAnswer(string answer, int questionId) {
            Tableta_Rosetta.ServiceReference1.AddAnswerRequest inValue = new Tableta_Rosetta.ServiceReference1.AddAnswerRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.AddAnswerRequestBody();
            inValue.Body.answer = answer;
            inValue.Body.questionId = questionId;
            Tableta_Rosetta.ServiceReference1.AddAnswerResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).AddAnswer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.AddAnswerResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.AddAnswerAsync(Tableta_Rosetta.ServiceReference1.AddAnswerRequest request) {
            return base.Channel.AddAnswerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.AddAnswerResponse> AddAnswerAsync(string answer, int questionId) {
            Tableta_Rosetta.ServiceReference1.AddAnswerRequest inValue = new Tableta_Rosetta.ServiceReference1.AddAnswerRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.AddAnswerRequestBody();
            inValue.Body.answer = answer;
            inValue.Body.questionId = questionId;
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).AddAnswerAsync(inValue);
        }
        
        public void RightAnswerSubmited(int questionId) {
            base.Channel.RightAnswerSubmited(questionId);
        }
        
        public System.Threading.Tasks.Task RightAnswerSubmitedAsync(int questionId) {
            return base.Channel.RightAnswerSubmitedAsync(questionId);
        }
        
        public void WrongAnswerSubmited(int questionId) {
            base.Channel.WrongAnswerSubmited(questionId);
        }
        
        public System.Threading.Tasks.Task WrongAnswerSubmitedAsync(int questionId) {
            return base.Channel.WrongAnswerSubmitedAsync(questionId);
        }
        
        public void AnswerShown(int answerId) {
            base.Channel.AnswerShown(answerId);
        }
        
        public System.Threading.Tasks.Task AnswerShownAsync(int answerId) {
            return base.Channel.AnswerShownAsync(answerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.GetRandomQuestionResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.GetRandomQuestion(Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequest request) {
            return base.Channel.GetRandomQuestion(request);
        }
        
        public Tableta_Rosetta.ServiceReference1.Question GetRandomQuestion() {
            Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequest inValue = new Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequestBody();
            Tableta_Rosetta.ServiceReference1.GetRandomQuestionResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetRandomQuestion(inValue);
            return retVal.Body.GetRandomQuestionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetRandomQuestionResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.GetRandomQuestionAsync(Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequest request) {
            return base.Channel.GetRandomQuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetRandomQuestionResponse> GetRandomQuestionAsync() {
            Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequest inValue = new Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetRandomQuestionRequestBody();
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetRandomQuestionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.RightAnswerResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.RightAnswer(Tableta_Rosetta.ServiceReference1.RightAnswerRequest request) {
            return base.Channel.RightAnswer(request);
        }
        
        public Tableta_Rosetta.ServiceReference1.RightAnswerInfo RightAnswer(int questionId) {
            Tableta_Rosetta.ServiceReference1.RightAnswerRequest inValue = new Tableta_Rosetta.ServiceReference1.RightAnswerRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.RightAnswerRequestBody();
            inValue.Body.questionId = questionId;
            Tableta_Rosetta.ServiceReference1.RightAnswerResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).RightAnswer(inValue);
            return retVal.Body.RightAnswerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.RightAnswerResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.RightAnswerAsync(Tableta_Rosetta.ServiceReference1.RightAnswerRequest request) {
            return base.Channel.RightAnswerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.RightAnswerResponse> RightAnswerAsync(int questionId) {
            Tableta_Rosetta.ServiceReference1.RightAnswerRequest inValue = new Tableta_Rosetta.ServiceReference1.RightAnswerRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.RightAnswerRequestBody();
            inValue.Body.questionId = questionId;
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).RightAnswerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.GetRandomWrongAnswers(Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequest request) {
            return base.Channel.GetRandomWrongAnswers(request);
        }
        
        public Tableta_Rosetta.ServiceReference1.WrongAnswersInfo GetRandomWrongAnswers(int questionId) {
            Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequest inValue = new Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequestBody();
            inValue.Body.questionId = questionId;
            Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetRandomWrongAnswers(inValue);
            return retVal.Body.GetRandomWrongAnswersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.GetRandomWrongAnswersAsync(Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequest request) {
            return base.Channel.GetRandomWrongAnswersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersResponse> GetRandomWrongAnswersAsync(int questionId) {
            Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequest inValue = new Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetRandomWrongAnswersRequestBody();
            inValue.Body.questionId = questionId;
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetRandomWrongAnswersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.GetQuestionStatistics(Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequest request) {
            return base.Channel.GetQuestionStatistics(request);
        }
        
        public Tableta_Rosetta.ServiceReference1.ArrayOfInt GetQuestionStatistics() {
            Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequest inValue = new Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequestBody();
            Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetQuestionStatistics(inValue);
            return retVal.Body.GetQuestionStatisticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.GetQuestionStatisticsAsync(Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequest request) {
            return base.Channel.GetQuestionStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsResponse> GetQuestionStatisticsAsync() {
            Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequest inValue = new Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetQuestionStatisticsRequestBody();
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetQuestionStatisticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.GetQuestionDataResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.GetQuestionData(Tableta_Rosetta.ServiceReference1.GetQuestionDataRequest request) {
            return base.Channel.GetQuestionData(request);
        }
        
        public Tableta_Rosetta.ServiceReference1.QuestionDataInfo[] GetQuestionData() {
            Tableta_Rosetta.ServiceReference1.GetQuestionDataRequest inValue = new Tableta_Rosetta.ServiceReference1.GetQuestionDataRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetQuestionDataRequestBody();
            Tableta_Rosetta.ServiceReference1.GetQuestionDataResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetQuestionData(inValue);
            return retVal.Body.GetQuestionDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetQuestionDataResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.GetQuestionDataAsync(Tableta_Rosetta.ServiceReference1.GetQuestionDataRequest request) {
            return base.Channel.GetQuestionDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.GetQuestionDataResponse> GetQuestionDataAsync() {
            Tableta_Rosetta.ServiceReference1.GetQuestionDataRequest inValue = new Tableta_Rosetta.ServiceReference1.GetQuestionDataRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.GetQuestionDataRequestBody();
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).GetQuestionDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tableta_Rosetta.ServiceReference1.UpdateDataResponse Tableta_Rosetta.ServiceReference1.WebService1Soap.UpdateData(Tableta_Rosetta.ServiceReference1.UpdateDataRequest request) {
            return base.Channel.UpdateData(request);
        }
        
        public void UpdateData(int questionId, int answerId, int subjectId, string questionText, string answerText, int countAsked, int countRight, double levelKnown) {
            Tableta_Rosetta.ServiceReference1.UpdateDataRequest inValue = new Tableta_Rosetta.ServiceReference1.UpdateDataRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.UpdateDataRequestBody();
            inValue.Body.questionId = questionId;
            inValue.Body.answerId = answerId;
            inValue.Body.subjectId = subjectId;
            inValue.Body.questionText = questionText;
            inValue.Body.answerText = answerText;
            inValue.Body.countAsked = countAsked;
            inValue.Body.countRight = countRight;
            inValue.Body.levelKnown = levelKnown;
            Tableta_Rosetta.ServiceReference1.UpdateDataResponse retVal = ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).UpdateData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.UpdateDataResponse> Tableta_Rosetta.ServiceReference1.WebService1Soap.UpdateDataAsync(Tableta_Rosetta.ServiceReference1.UpdateDataRequest request) {
            return base.Channel.UpdateDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tableta_Rosetta.ServiceReference1.UpdateDataResponse> UpdateDataAsync(int questionId, int answerId, int subjectId, string questionText, string answerText, int countAsked, int countRight, double levelKnown) {
            Tableta_Rosetta.ServiceReference1.UpdateDataRequest inValue = new Tableta_Rosetta.ServiceReference1.UpdateDataRequest();
            inValue.Body = new Tableta_Rosetta.ServiceReference1.UpdateDataRequestBody();
            inValue.Body.questionId = questionId;
            inValue.Body.answerId = answerId;
            inValue.Body.subjectId = subjectId;
            inValue.Body.questionText = questionText;
            inValue.Body.answerText = answerText;
            inValue.Body.countAsked = countAsked;
            inValue.Body.countRight = countRight;
            inValue.Body.levelKnown = levelKnown;
            return ((Tableta_Rosetta.ServiceReference1.WebService1Soap)(this)).UpdateDataAsync(inValue);
        }
    }
}
